#!/bin/bash

case $1 in
"sum") echo $[ $2 + $3 ];;
"sub") echo $[ $2 - $3 ];;
"mul") echo $[ $2 * $3 ];;
"div") if [ $3 -eq 0 ]
       then echo "Error: division by zero"
       else echo $[ $2 / $3 ]
       fi
       ;;
*) echo "Error: operation not found";;
esac
