#!/bin/bash

if ! [[ -f $1 ]]
then
echo "Error: no such file" >&2
exit -6
     elif [[ "$#" -ne 2 ]]
     then
     echo "Error: not enough arguments" >&2
     exit -10
        elif [[ -r $1 && -w $2 ]]
          then
	   tac $1 >> $2
	else
	   echo "Error: permission denied" >&2
           exit -8
fi

