#!/bin/bash

[[ -z "$1" && -z "$2" ]] && {
    echo "Error: enter both arguments" >&2
    exit -4
}

if [[ -d "$1" ]]
then
    grep -IRs $2 $1
else
    echo "Error: no such directory" >&2
    exit -5
fi
