#!/bin/bash

if ! [[ -f $1 ]]
then
echo "Error: no such file" >&2
exit -6
     elif [[ "$#" -ne 2 ]]
     then
     echo "Error: not enough arguments" >&2
     exit -10
else
 if [[ -e $2 ]]
   then
   if [[ -r $1 && -w $2 ]]
           then
	    if [[ "$1" != "$2" ]]
		then
       	         tac $1 > $2
   		else
		cat $1 > tmp
		tac tmp > $2
		rm tmp
	    fi
	   else
	    echo "Error: permission denied" >&2
            exit -8
	  fi
        else
          if [[ -r $1 ]]
          then
	     tac $1 > $2
          else
	   echo "Error: permission denied" >&2
          fi
	fi
fi

