#!/bin/bash

cd ~

last_backup_date="$(ls | grep "^Backup-" | sort -n | tail -1 | cut -d "-" -f 2,3,4)"
if [[ ! -d restore ]]
	then
	mkdir restore
fi

cd "Backup-$last_backup_date"

backup_files="$(ls)"

for file in $backup_files; do
	not_copy=$(echo $file | grep -ao '[A-Za-z0-9]{1,}-[0-9]{4}-[0-9]{2}-[0-9]{2}')
	if [[ "$file" != "$not_copy" ]]
		then
		cp $file ~/restore
	fi
done
